config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:show]
  root 'default#index'
  get "/search", to: "users#search", as: "search"
  resources :users, only: [:new, :show, :create] do
    resources :items, except: [:destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]

  get 'register', to: 'users#new', as: 'register'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  media_item :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  active     :boolean          default("t")
#

class Item < ActiveRecord::Base
  belongs_to :user
  validates :media_item, presence: true, length: {within: 10..200}

  scope :just_active, -> { where(active: true) }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :items
  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true,
            length: {maximum: 100},
            format: {with: EMAIL_FORMAT},
            uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 5}

  before_save do
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "You are not authorized for this page" if current_user.nil?
  end
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController
  def index
    @users = User.all
    @items = Item.count
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authorize
  before_filter :find_user, only: [:new, :create, :index, :show, :edit, :update]

  def index
    if params[:item]
      @items = @user.items.where('media_item LIKE ?', "%#{params[:item]}")
    else
      redirect_to user_path(@user)
    end
  end

  def new
    @item = @user.items.build
  end

  def create
    @item = @user.items.build(item_params)
    if @item.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @item = @user.items.find(params[:id])
  end

  def edit
    @item = @user.items.find(params[:id])
  end

  def update
    @item = @user.items.find(params[:id])
    if @item.update(item_params)
      redirect_to user_item_path(@user, @item)
    else
      render :edit
    end

  end

  private
  def find_user
    @user = User.find(params[:user_id])
  end

  def item_params
    params.require(:item).permit(:media_item, :active)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @items = @user.items.just_active
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "You are now logged in #{user.name}"
    else
      flash.now.alert = "Email or password invalid. Please fix them"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thx you! #{@user.name}"
    else
      render :new
    end
  end

  def search
    if params[:item]
      Item.search(params[:item])
      render 'show'
    else
      redirect_to @user, notice: "nothing to show"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/default/index.html.erb
<h2>Amazin user with amazin items to show. All the images with casts came from here!</h2>

<h4>We have <%= pluralize(@users.count, "user") %></h4>
<h4>We have <%= pluralize(@items, "item") %></h4>

<% unless current_user %>
    <strong>Register now!</strong>
    <%= link_to "Register", new_user_path %>
<% end %>

<p>Check out for this users!!!</p>

<% @users.each do |user| %>
    <%= link_to user.name, profile_path(user) %>
<% end %>

app/views/items/edit.html.erb
<p>Edit an item here:</p>

<%= form_for([@user, @item]) do |f| %>
    <% if @item.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :media_item %><br/>
      <%= f.text_field :media_item %>
    </div>

    <div class="field">
      <%= f.label :active %><br/>
      <%= f.check_box :active %>
    </div>
    <div class="actions"><%= f.submit "Update this item!" %></div>
<% end %>

app/views/items/index.html.erb
<p>hi, <%= @user.name %></p>

<p>for the query:<strong> <%= params[:item] %> </strong>we found <%= pluralize(@items.count, "item") %></p>

<% @items.each do |item| %>
    <ul>
      <li>
        <%= item.media_item %>
      </li>
    </ul>
<% end %>

<%= link_to "Back to your profile", user_path(@user) %>

app/views/items/new.html.erb
<p>Hello <%= @user.name %>, Add a new and amazing item here! </p>
<%= form_for([@user, @user.items.build]) do |f| %>
    <% if @item.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :media_item %><br/>
      <%= f.text_field :media_item %>
    </div>

    <div class="field">
      <%= f.label :active %><br/>
      <%= f.check_box :active %>
    </div>
    <div class="actions"><%= f.submit "Add a new item!" %></div>
<% end %>

app/views/items/show.html.erb
<p>Items for this user: <%= @user.name %></p>

<h3>
  <%= @item.media_item %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserItems</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="small">
  <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log Out", logout_path %>
  <% else %>
      <%= link_to "Register", register_path %> or
      <%= link_to "Log In", login_path %>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/profiles/show.html.erb
<h2>This is the public profile for: <%= @user.name %></h2>

<strong>Only <%= pluralize(@items.count, "item") %> for now...</strong>

<div>
  <% @items.each do |item| %>
      <p>
        <%= item.media_item %>
      </p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Register</h1>
<em>Register here to add items. The internet will judge you.</em>
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br/>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br/>
      <%= f.password_field :password %>
    </div>

    <div class="actions"><%= f.submit "Register" %></div>
<% end %>

app/views/users/show.html.erb
<p>Hello <%= @user.name %></p>

<h3>This is your personal profile</h3>
<div class="note">
  <p>Until now you have created  <%= pluralize(@user.items.count, "item") %></p>
</div>
<div>
  <%= link_to "public profile", profile_path(@user) %>
</div>
<div>
  <%= link_to "Create new Item", new_user_item_path(@user) %>
</div>

<p>Search here for your items</p>
<%= form_tag user_items_path(user_id: @user.id), method: :get do %>
    <%= label_tag :item %>
    <%= text_field_tag :item %>
    <%= submit_tag "Search" %>
<% end %>

<h3>Here are your items:</h3>
<% @user.items.each do |item| %>
    <ul>
      <%= item.media_item %>
      <%= link_to item.media_item, user_item_path(@user, item) %>
      <%= link_to "Edit", edit_user_item_path(@user, item) %>
    </ul>
<% end %>